# Generated by Django 4.1.7 on 2023-03-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blocked_at",
            field=models.DateField(default=None, null=True),
        ),
    ]
