# Generated by Django 4.1.7 on 2023-03-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_blocked_at_user_blocked_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="blocked_until",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
