# Generated by Django 4.1.7 on 2023-03-08 22:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("followings", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="following",
            name="email_sent",
        ),
        migrations.RemoveField(
            model_name="following",
            name="last_check",
        ),
    ]
