# Generated by Django 4.1.7 on 2023-03-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("followings", "0003_remove_following_email_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="following",
            name="last_email_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
