# Generated by Django 4.1.7 on 2023-03-08 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loans", "0001_initial"),
        ("copies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="copy",
            name="users",
            field=models.ManyToManyField(
                related_name="current_books",
                through="loans.Loan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
